### ISSUE TITLE
コーディング規約

### ISSUE THREAD

**Issue by kujiy** [xoopscube/legacy#116]
いつも素敵なプロジェクトをありがとうございます。

普段私は[php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) で自動整形しているのですが、xoopsのファイルは必ず自動整形されてしまいxupdateの度にぶつかるので困っています。
（急いで書いたコードでコアハックしているものもあるため）

PSR2など、xoopsには何らかのcoding standardがあるのでしょうか。
ゆるゆるのrulesetでもいいので、何かしら基準を教えていただけますと助かります。
できればfixerはphp-cs-fixerで、rulesetはこれです、といったところまで教えていただきたいです。

よろしくお願い致します。

**Comment by kilica** [comment]
残念ながらコーディング規約などは整備されていません。
PHP4の頃からのコードも残っており、コミッタによってバラバラになっています。
独自にコーディング規約を決めると揉めるだけですので、今でしたらPSR2にするのが良いのではないかと思っています（僕が最近書いているコードは、なるべくそうしています）。
どうでしょうか？ > @nao-pon さん、みなさん

**Comment by nao-pon** [comment]
そうですね。コードスタイルが混在している現状では手を入れる時にも結構気を使いますので、私も PSR-2 で統一できたらいいなと思います。

**Comment by kujiy** [comment]
みなさんありがとうございます。経験上、動いているファイルをphp-cs-fixerのPSR-2でfixしてコケたことはありません。例え1行の変更だとしてもファイル全体を更新したdiffになってしまいますが、

> 手を入れる時にも結構気を使いますので、

この心理的な負担は大きいので、もし私が変更ファイルをpushするタイミングがありましたら、そのままpushさせていただきたいと思います（もちろんcommit messageにはその旨書きます）。
そうするとxupdateをもっと気軽に活用できるようになりますし、コードも新し目のものになるので（class内の`function`が`public function`になる等）助かります。

**Comment by nao-pon** [comment]
変更をコミットする前に一度 CS to PSR-2 などとして一つコミットして頂くと、変更分が分かりやすくてよいと思いますが如何でしょうか。
それか、一度全ての PHP ファイルを PSR-2 にしてコミットするほうがいいのかな？

**Comment by kujiy** [comment]
@nao-pon そうですね、` CS to PSR-2` が良かったですね。

> それか、一度全ての PHP ファイルを PSR-2 にしてコミットするほうがいいのかな？

可能なのであれば、これがベストだと思います。fixer使えば一瞬で終わりますし、人間がやるより安全です。
参考までに、私の社内プロジェクトはすべてそうしました。
デメリットは２つあります。

1. 個別ファイルのlogが見たいときに必ずそのコミットが最新として出てしまう
    - ２つめ移行のlogを見ればいいだけなのでメンバーから不満は出ませんでした。
2. 個別ファイルのblameが全行そのコミットになってしまう
    - （300行目を最後に変えた人が知りたい場合、など）
    - 検索対象をそれ以前のrevisionにすれば解消できる
        - そもそもblameする人が少ないのか、これも不満は出ませんでした。
        -  （私は少し不満でしたがそれを上回るメリットのほうが何十倍も大きかったです）
    
可能であれば、ぜひPSR-2にしてしまっていただきたいです。

**Comment by nao-pon** [comment]
とりあえず PSR-2 でブランチを作ってみました。

- https://github.com/xoopscube/legacy/tree/psr2

**Comment by kujiy** [comment]
:+1: ありがとうございます。indentやカンマ後ろのスペースが入るだけで全然違いますね。editする場合はそのbranchを使わせて頂きます。

ここはcloseした方がいいでしょうか。

**Comment by nao-pon** [comment]
psr2 を master にマージしました。
ただ、X-update で導入される legacy は XoopsX のリポジトリのものなので、開発ブランチの https://github.com/XoopsX/legacy (pilot ブランチ) からチェックアウトするのがよいかと思います。
