### ISSUE TITLE
ユーザのパスワードがsaltなしのMD5で保存されている

### ISSUE THREAD

**Issue by kujiy** [xoopscube/legacy#117]
この問題はxoopsxを企業が利用できない大きな理由になっていると思います。

最低でもsha1にしたいのですが、既存システムを移行させるのは面倒なので（パスワード変更依頼画面などを用意しないといけない）、新規システムだけでもそうすることができないでしょうか。

するとすれば、どのような作りにするべきでしょうか。

過去のトライやプラクティスがあれば教えていただきたいです。

**Comment by kilica** [comment]
後々使い回しできるように、と考えるのであれば、パスワード絡みで md5 している箇所をデリゲートで置き換えるのがよいかと思います。

### html/preload/PasswordPreload.class.php

新規ファイル。どの暗号化方法で暗号化するかをサイトごとにこのファイルで指定する。

```php
class PasswordPreload extends XCube_ActionFIlter
{
    public function preBlockFilter()
    {
        $this->mController->mRoot->mDelegateManager->add("Site.Encrypt", array(&$this, "encryptPassword"));
    }

    public function encryptPassword(&$password)
    {
        // encrypt password process like sha1, sha2, md5, or your own
        $password = sha1($password);
    }
}
```

### html/kernel/member.php

`md5($pwd)` している部分を、以下のように `XCube_DelegateUtils::call('Site.Encrypt', new XCube_Ref($pwd))` で置き換える。
`PasswordPreload::encryptPassword()` が呼ばれて暗号化される。

```php
function &loginUser($uname, $pwd)
{
    $criteria = new CriteriaCompo(new Criteria('uname', $uname));
    XCube_DelegateUtils::call('Site.Encrypt', new XCube_Ref($pwd));
    $criteria->add(new Criteria('pass', $pwd));
    $user =& $this->_uHandler->getObjects($criteria, false);
    if (!$user || count($user) != 1) {
/// 略
}
```

**Comment by kujiy** [comment]
@kilica コード付き！ありがとうございます。
実は手元でコアハックしてやっていまして、問題が３つあります。

1. 新しいパスワードを定義する
    - @kilicaさんのpreloadで解消（ありがとうございます！）
2. DBの`password`カラムが`varchar(32)`（sha1は40, sha2は64byteとか）
    - preloadでalter tableしちゃう？
    - きちんとmodule化してinstallプロセスを踏む？
3. そのbyte数チェックを[20個近いファイル](https://github.com/xoopscube/legacy/search?utf8=%E2%9C%93&q=%27pass%27%2C+*+32)でやっている
    - 全部変数に書き換える

xoopsの作り、流儀がわかっていない自分が片手間で3をやるのはどうかなと思ったりしていますが、
とりあえず、もし@kilicaさんがやるとしたら、2,3にどうアプローチするのか教えていただけますと助かります。

**Comment by kilica** [comment]
そうですね、桁数が短すぎますねえ。
まあ上策を取るなら当然 3. になりますね。

とりあえず自分だけで使うのであれば、myuser モジュールを作って、user モジュールと換装して使う、かな。具体的な方法は、もうしばらくお待ち下さい。

**Comment by kujiy** [comment]
@kilica ありがとうございます。なるほど、userモジュールを差し替えてしまうということですか。
思いつきませんでした。確かにそれが一番良さそうな気がします。それができれば、私が一通り進化させた後に、いずれ既存userモジュールと差し替えなどということもありえるかも。（やろうと思えば）切り替えて使えるというのは既存システムの移行方法を考える際にも選択肢が多くなりそうで、いいですね。

**Comment by hodade** [comment]
xoopsのmd5はゆゆしき問題ですね。
@kilica さんのuserモジュール換装案がいい気がするのでぜひ詳細が知りたく思います。

**Comment by kujiy** [comment]
既存管理者/ユーザに負担を掛けないのであれば、いずれにしても or 文で新旧処理を分けるしかないですよね。

- 新規インストールは32byte以上のmysqlカラムにする
- コアロード時の処理でカラムのbyte数を見て新旧モード判別
- ユーザ登録・認証処理は新旧で処理を分ける
- htmlの桁数制限はあまり意味が無いのでなくす（パスワード登録時だけ制限あり）

こんな感じですかねぇ。それぞれの処理について具体的にどのファイルでやるかアドバイスいただけますと助かります。 @kilica

**Comment by kujiy** [comment]
みなさんにご対応いただき `password_hash()` を利用したセキュアな仕組みになりました。

次期リリースでxupdateに取り込まれるものと思われます。

大変ありがとうございました。 @RyujiAMANO @nao-pon  @kilica
