### ISSUE TITLE
PHP reports many error "Only variables should be passed by reference" on PHP 7.1

### ISSUE THREAD

**Issue by nao-pon** [xoopscube/legacy#123]
I think that most of them are receiving CriteriaCompo::add() with the first argument as reference specification. Probably it needless to receives by reference.

**Comment by kilica** [comment]
たしかに、何を意図して参照渡しにしてるんでしょうね。うーん。

**Comment by Ohsepoa** [comment]
thanks

**Comment by nao-pon** [comment]
Currently this patch applied to [XOOPS X pilot branch](https://github.com/XoopsX/legacy). Please try and check it.
