### ISSUE TITLE
passwordNeedsRehash はパスワード変更を強制しますか？

### ISSUE THREAD

**Issue by kujiy** [xoopscube/legacy#127]
パスワード強化 #117 のご対応をいただきありがとうございます。xoopsコミュニティのすごさに圧倒されております 😺 

さて、ソースを眺めていて少し教えていただきたいことがありました。

`passwordNeedsRehash` が発動したときの動きが `edituser.php` へ遷移させパスワード変更を促すように見えます。（コードから想像で話しています）

https://github.com/xoopscube/legacy/pull/126/files#diff-39ce912f7a253bb0bc8a0d3308e1c574R294

とても素敵な動きだと思いました！
と同時に、ログイン時に入力されたpwを使ってrehashすれば、ユーザの入力負担が減るのでさらに嬉しいのでは？と思いつきました。

うちの使い方が特殊なんですが、ユーザにpw変更をさせない（ひどい）運用をしておりまして、edituser.php自体を隠しているxoopsが多数あります。知っているところでもpwをexcel管理しているところもあるので、地味に影響大きいのではと思ったりしまして（運用が悪いのはわかっているのですが、なりすまし機能がない限り管理者はユーザのpwを知っていないとサポートできないのです）

まあそれは置いておいて、使うユーザとしては "裏でこっそりrehash" の方が嬉しいかな～と思ったりしたのですが、そういう選択肢はありでしょうか？ @nao-pon

**Comment by nao-pon** [comment]
@kujiy 開発当初はそのような動作をしていましたが、途中で自動更新できることに気付いて、自動更新される仕組みになっています。

- https://github.com/xoopscube/legacy/pull/126/files#diff-39ce912f7a253bb0bc8a0d3308e1c574R268

ここで自動更新に失敗した時に edituser.php へ移動してパスワード更新を促すようになっています。まあ、自動更新に失敗することはほぼないはずなので、この部分はまず実行されないと思います。

**Comment by kujiy** [comment]
あ、そうだったんですね！お手数をおかけしました！ありがとうございました 😸
