### ISSUE TITLE
[FEAT]: Preload Dashboard moved to admin 

### ISSUE THREAD

**Issue by gigamaster** [xoopscube/legacy#217]
### Description

Replace preload dashboard in /admin

**Comment by gigamaster** [comment]
AdminDashboard is used to manage rendered blocks, sort of raw option having logical equivalence to block management.
Simple bool 0 | 1 to disable and enable the dashboard template and block render.  
Usage in admin_theme.html :  

### Smarty Block

```smarty
<{* Smarty Render Block if enabled in AdminDashboard *}>
<{$xoops_lblocks.block_overview.content}>
```

### Smarty Block loop (all)

```smarty
    <{foreach name='lblock' item='block' from=$xoops_lblocks}>
        <{if $block.name !='sidemenu' && $block.name !='action_search'}>
            <div class="ui-card-block">
            <h3><{$block.title}></h3>
                <div class="block-content">
                    <{$block.content}>
                </div>
            </div>
        <{/if}>
    <{/foreach}>
```  

**Note** that Smarty Blocck Loop prevents rendering of blocks 'sidemenu' and 'action_search'  
since these blocks are placed in the  in the side panels of admin_theme.

**Comment by nbuy** [comment]
Well, I think this issue problem.

There is `class Legacy_AdminDashboard` both legacy/preload/ AdminDashboard.class.php and legacy/admin/preload and loaded both.

XCL preload name space is flat.  Duplicate class will be different beheiver in PHP version.
(PHP 8.2 to be crach, older may be working?)

**Comment by gigamaster** [comment]
Hmm, I should check the last commit, because I lost internet and XCL 2.3.x only runs Admin Preload Dashboard.
What I understand from @kilica comment on "preloads" is that
Dashboard should only run for admin ( /legacy/admin/preload/...)
Not all the time with /legacy/preload/... 
But maybe the last commit doesn't reflect the changes to Dashboard and to User Interface.
Thanks for opening this. I'm compare the differents packages and PHP versions for next update.
^_^/

**Comment by nbuy** [comment]
Thanks comment.

This is problem the class duplicate handling in PHP. 
Older is loose (probably override), Newer is strict (rise Fatal error).
