### ISSUE TITLE
[BUG]: Type Safe Element tray flag PHP8

### ISSUE THREAD

**Issue by gigamaster** [xoopscube/legacy#243]
### Which module?

legacy

### Description of the bug

There are some notices due to strict requirements
Example, the $fag usage in templates, fix :  

```diff
-    <{if $flag}>
+   <{if isset($flag)}>
```
Elementtray
```smarty
<{foreach from=$tray->getElements() item=element}>
    <{if isset($flag)}>
        <{$tray->getDelimeter()}>
    <{/if}>
...
```

### Steps To Reproduce

1. login to admin
2. altsys or any core module using $flag
3. PHP8 notices

**Comment by nbuy** [comment]
```
-    <{if $flag}>
+   <{if isset($flag)}>
```
I think this is confuse.
When `$flag = 0;` that how work it.

Probabably you want like this.
```
-    <{if $flag}>
+   <{if !empty($flag)}>
```
Umm, Not smart.

**Comment by gigamaster** [comment]
Thanks @nbuy ^_^/
