### ISSUE TITLE
Many  strict standards errors in PHP 5.3

### ISSUE THREAD

**Issue by suin** [xoopscube/legacy#35]
If `error_reporting` setting includes `E_STRICT` a lot of strict standard errors are reported.

```
error_reporting =  E_ALL | E_STRICT
```

**Comment by orrisroot** [comment]
I think, this issue is already gone on the latest sources.
I suggest to close this issue and let's discuss about PHP 7 instead of PHP 5.3.

**Comment by gigamaster** [comment]
Update XCL 2.3 PHP7
