### ISSUE TITLE
Module option parameter at general setting values are always last one.

### ISSUE THREAD

**Issue by bluemooninc** [xoopscube/legacy#39]
Mr.Kuriyama reports issue at Facebook.

modules/legacy/admin/class/ModuleInstallInformation.class.php line450
- $this->mOptions[] =& $option;
- $this->mOptions[] = $option;

xcl2.1、xcl2.2 same.

I suppose is issue occur at PHP 5.3 or later.

**Comment by gigamaster** [comment]
Update XCL 2.3 PHP 7
