### ISSUE TITLE
Better to change the name of "ユーザーグループ管理" to "グループ管理"

### ISSUE THREAD

**Issue by nouphet** [xoopscube/legacy#45]
ユーザーモジュールのグループを管理するところが「ユーザーグループ管理」になっているけど「グループ管理」を探しにくい（というかグループを管理できることを知らない人が多い）ので、

「ユーザーグループ管理」を「グループ管理」に変更することを提案します。

なお、英語版は最初から Group Management になってます。

**Comment by gigamaster** [comment]
Branch 2.3 moved to New Repo XCL
